import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { Footer } from "@/components/Footer";
import { SearchProvider } from "./bookings/context/useSearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          "h-full m-0 w-full font-sans antialiased",
          inter.className
        )}><SearchProvider>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem>
          <Navbar />
           {children}
          <Footer />
        </ThemeProvider></SearchProvider>
      </body>
    </html>
  );
}
